
import { ListView, Palette, ScrollView, LineEdit, Button, StandardButton } from "std-widgets.slint";
import { Code } from "codes_page.slint";

export component AddCodePage inherits Rectangle {
  in property <image> camera <=> camera.source;
  callback add_code(name: string, secret: string);
  callback navigate_to_start_page();

  camera := Image {
    image-fit: contain;
  }

  VerticalLayout {
    Rectangle {
      vertical-stretch: 1;
    }

    Button {
      text: "temp";
      clicked => {
        root.add_code("NAME", "SECRET");
        root.navigate_to_start_page();
      }
    }
  }
}